name: Build
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'mystaticsite/**'
jobs:
  deploy-content:
    runs-on: ubuntu-latest
    container: milldr/static-site-deployer
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - 
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - 
        name: "Deploy static content to S3 with Hugo"
        run: |  
          cd ./mystaticsite
          hugo -D
          hugo -v deploy --maxDeletes 1000
